externalNullifier = ""
identitySecret = ""
messageId = ""
pathElements = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
pathSelectors = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
userMessageLimit = ""
x = ""
